#79: Creating Data Points For 3D Graph
UniversityOfSaskatchewanCMPT371/term-project-2024-team-2 pull request #106
Opened 2024-02-08 02:55 UTC by Subzeero

Closes #79 

# What was the issue
One of our core requirements for our project requires a plot for analyzing data. This PR includes one of the necessary components for this plot: the data points. 

# What was done and why
I created two React components: DataPoint and DataPointMenu. The DataPoint component will represent each point of data that will be plotted. The DataPointMenu appears when a DataPoint is selected and it display information about the DataPoint. The selected point is shared using a PointSelectionContext which stores the selected DataPoint id number in its state.

# How it was tested
I used the WebXR emulator to test the requested functionality.

2024-02-08 03:03 UTC, Jesster2829 requested changes
Just add documentation otherwise good to go

2024-02-08 03:03 UTC, Jesster2829 commented on my-webxr-app/src/App.tsx
> +            {/*<RotatingBox position={[-0.8, 1.5, -1]} />*/}
Can probably remove this commented out code

2024-02-08 03:03 UTC, Jesster2829 commented on my-webxr-app/src/contexts/PointSelectionContext.tsx
> +};
Add some documentation for what is happening here

2024-02-08 04:07 UTC, Subzeero commented
Addressed the review concerns. Also fixed the minor issue when two controllers hovered over the same DataPoint and the hover effect was prematurely removed. Simply switched from a Boolean state to a count of hovers.

2024-02-08 05:44 UTC, LongQuanNguyen reviewed
The components folder is with 'C' capitalized. Should it be in lowercase?

2024-02-08 21:20 UTC, matthew-buglass requested changes
We just need to add unit tests for the components

2024-02-08 21:20 UTC, matthew-buglass commented on my-webxr-app/src/components/DataPoint.tsx
Needs unit tests

2024-02-08 21:20 UTC, matthew-buglass commented on my-webxr-app/src/components/DataPointMenu.tsx
needs unit tests

2024-02-08 21:20 UTC, matthew-buglass commented on my-webxr-app/src/contexts/PointSelectionContext.tsx
needs unit tests

2024-02-08 22:53 UTC, LongQuanNguyen commented on my-webxr-app/src/contexts/PointSelectionContext.tsx
> +  createContext<PointSelectionContext | null>(null);
Yes, Comment resolve during pairing

2024-02-08 22:55 UTC, LongQuanNguyen commented on my-webxr-app/src/contexts/PointSelectionContext.tsx
> +  const context = useContext(PointSelectionContext);
The object is returned so it is guaranteed to be not null -- per discussion during paring

2024-02-10 02:39 UTC, Jesster2829 approved these changes
Pre approval before commit, have witnessed all changes in chat but will push after his assignment is done

2024-02-10 05:54 UTC, merged