#78 Creating 3D Axis For Plotting Data Points
UniversityOfSaskatchewanCMPT371/term-project-2024-team-2 pull request #111
Opened 2024-02-08 19:48 UTC by qpb948

Closes #78

Closes #<insert_issue_number>

# What was the issue
We needed a 3D axis to plot data points onto so we can visualize the data.  This axis needed to scale based on input as well, so the numbers on the axis will adjust based on a minimum and maximum value that will be read for the CSV (currently just hardcoded values). This PR includes the 3D axis that will be used.

# What was done and why
I created 3 new files: axis.tsx, singleAxis.tsx, and createTIcks.tsx.
axis.tsx calls the component in singleAxis.tsx 3 times, one for each axis (x, y, z).
singleAxis.tsx calculates the range of values that will be displayed on the axis, as well as creating the axis depending on input from axis.tsx.
createTicks.tsx this file creates and positions the ticks and labels correctly on each axis.

# How it was tested
Testing in the WebXR emulator. I put in different values for minValue and maxValue in App.tsx to ensure functionality of scaling works as required.

2024-02-08 21:12 UTC, Jesster2829 approved these changes
Looks good to me! Thank you for adding in the documentation

2024-02-08 22:41 UTC, matthew-buglass requested changes
Looks good to me. Just need to put in some unit tests.

2024-02-08 22:41 UTC, matthew-buglass commented on my-webxr-app/src/Components/axis.tsx
Need some unit tests.

2024-02-08 22:41 UTC, matthew-buglass commented on my-webxr-app/src/Components/createTicks.tsx
Need some unit tests.

2024-02-08 22:41 UTC, matthew-buglass commented on my-webxr-app/src/Components/singleAxis.tsx
Need some unit tests.

2024-02-10 04:25 UTC, matthew-buglass commented
Also, make sure the "Components" directory gets renamed to "components"

2024-02-10 05:43 UTC, merged