#15 - initial draft, backend mostly complete, but frontend is relying…
UniversityOfSaskatchewanCMPT371/term-project-2024-team-2 pull request #174
Opened 2024-03-08 02:36 UTC by qpb948

Closes #15 

# What was the issue
Implementing selection of data that will represent XYZ axes.

# What was done and why
Implemented ways to filter out columns that are not integers and a way to get XYZ axes through a column name.
I plan on having the user click a button and have a menu pop up that lists the possible column names that can be used for XYZ axes. Then three text boxes that will be linked to XYZ axes. Also created a max function that will get the max value from the XYZ axes selected so the range is correctly displayed on the 3D axis.

# How it was tested
Create units tests ensuring the functionality of the methods created. Plan on creating more unit tests when front end is being implemented.

2024-03-26 02:48 UTC, matthew-buglass requested changes
Overall, pretty good. A few notes:
- To full test this and as a interim fix until the adding of data is hooked up, we can have the DAL methods return static values so we can make sure that this part works when we're using it.
- Really need to beef up the pre- and post-conditions and add more docstrings.
- I need to see some descriptions and ideally screenshots of what this looks like while the app is being run.

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/App.tsx
> +// import SelectAxesColumns from './components/SelectAxesMenu';
Why is this commented out?

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/components/SelectAxesButton.tsx
> +// import SelectAxesColumns from './SelectAxesMenu';
Why is this commented out?

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/components/SelectAxesMenu.tsx
> + */
Pre and post-conditions

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/components/SelectAxesMenu.tsx
> + */
Pre and post-conditions

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/repository/DbRepository.tsx
> + */
Pre and post-conditions

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/repository/DbRepository.tsx
> +         */
Pre and post-conditions

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/repository/DbRepository.tsx
To mock out the behaviour while we are still waiting for the DAL to finish, we can just have there return static value so we can at least see it doing something.

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/repository/FilterAxis.tsx
> +}
Doc strings. Pre and post-conditions.

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/repository/GetMaxXYZRange.tsx
> +}
Doc string. Pre and post-conditions

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/utils/GetColumnNames.tsx
> +export async function getColumnTitles(dbName: string): Promise<string[]> {
Doc string. Pre and post-conditions

2024-03-26 02:48 UTC, matthew-buglass commented on my-webxr-app/src/utils/GetColumnNames.tsx
> +export async function setRepresentingColumns(
Doc string. Pre and post-conditions

2024-03-29 19:59 UTC, matthew-buglass requested changes

2024-03-29 19:59 UTC, matthew-buglass commented on my-webxr-app/src/components/SelectAxesMenu.tsx
> + */
Params should be listed each on their own line

2024-03-29 19:59 UTC, matthew-buglass commented on my-webxr-app/src/components/SelectAxesMenu.tsx
> + */
Params should be listed each on their own line

2024-03-29 19:59 UTC, matthew-buglass commented on my-webxr-app/src/contexts/AxesSelectionContext.tsx
> +// import * as log4js from "log4js";
Delete

2024-03-29 19:59 UTC, matthew-buglass commented on my-webxr-app/src/contexts/AxesSelectionContext.tsx
> + */
pre- and post- conditions

2024-03-29 19:59 UTC, matthew-buglass commented on my-webxr-app/src/contexts/AxesSelectionContext.tsx
> +    //   );
delete

2024-03-29 19:59 UTC, matthew-buglass commented on my-webxr-app/src/contexts/AxesSelectionContext.tsx
> +    //   );
delete

2024-03-29 19:59 UTC, matthew-buglass commented on my-webxr-app/src/contexts/AxesSelectionContext.tsx
> +    //   );
delete

2024-03-29 19:59 UTC, matthew-buglass commented on my-webxr-app/src/contexts/AxesSelectionContext.tsx
> + */
pre- and post-conditions

2024-03-30 20:04 UTC, matthew-buglass requested changes
Just a few minor syntax things, but otherwise looks great!

2024-03-30 20:04 UTC, matthew-buglass commented on my-webxr-app/src/contexts/AxesSelectionContext.tsx
> + */
Missing a `@return`

2024-03-30 20:23 UTC, Aesha7 commented on my-webxr-app/src/components/SelectAxesMenu.tsx
> +    _setSelectedZAxis: React.Dispatch<React.SetStateAction<string | null>>,
I needed to create new variable names and setSelectedXAxis and setXAxis were already used.

2024-03-30 23:54 UTC, matthew-buglass approved these changes
Looks great!

2024-03-31 00:28 UTC, merged