199 smoke test for display points gherkin
UniversityOfSaskatchewanCMPT371/term-project-2024-team-2 pull request #235
Opened 2024-03-28 07:00 UTC by qpb948

Closes #199 

# What was the issue
Needed smoke test for gherkins.

# What was done and why
Created a smoke test for displaying data points. Used test hooks to log to a file and then search the log for the correct hooks.

# How it was tested
I walked through the system and tested the test hooks go to the log, and ensure the output is correct. And the test cases pass.

2024-03-28 17:39 UTC, Subzeero requested changes
It looks like Git messed up some thing in the PointSelectionContext

2024-03-28 18:15 UTC, MitchWag01 reviewed
Is there any way for us to verify that specified data has actually shown up? just looking through the gherkin it says the data point displays "specified" data? could we possibly check that its showing the correct information?

2024-03-29 02:38 UTC, qpb948 commented on my-webxr-app/src/contexts/PointSelectionContext.tsx
I believe I replaced it correctly, if you could take a look to double check. thanks

2024-03-29 04:26 UTC, Subzeero approved these changes
Looks good 👍

2024-03-29 17:18 UTC, LongQuanNguyen approved these changes
Good works!

2024-04-02 00:30 UTC, merged