249 fix hard coded point scale factor
UniversityOfSaskatchewanCMPT371/term-project-2024-team-2 pull request #250
Opened 2024-03-31 19:11 UTC by LongQuanNguyen

Closes #249

# What was the issue
The scale value for scaling the graph was hard coded to the point, leading to the point staying in the same position even when the graph is scaling.

# What was done and why
Allow scale to be passed in when creating data point positions so that the position of points will change relative to the graph scaling.

# How it was tested
Visually confirmed, WIP

2024-03-31 21:09 UTC, Subzeero reviewed
Nice, that video looks good 🙌

There's a few bits of commented out code that we should probably remove before merge?

2024-03-31 23:09 UTC, LongQuanNguyen commented
I notice GenerateXYZ also takes in hardcoded maxValues. I have modified it to get them form DB now. As a result, when u first run the app, there will be no tick on the axis until the columns are selected.

https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/assets/94843824/f2ae5d43-baf1-4804-9dc8-0102b8f1d0a1

2024-03-31 23:11 UTC, LongQuanNguyen commented on my-webxr-app/tests/components/GenerateXYZ.test.tsx
> +  //       0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100].map(String));
Waiting to pair with Zander on why the max values are not returned here, leading to no ticks getting rendered.

2024-04-01 17:08 UTC, matthew-buglass requested changes

2024-04-01 17:08 UTC, matthew-buglass commented on my-webxr-app/src/App.tsx
> +// ];
Remove the commented-out code
```suggestion
```

2024-04-01 17:08 UTC, matthew-buglass commented on my-webxr-app/src/App.tsx
> +// await DAL.storePCA(await DAL.getAvailableFields());
Remove the commented-out code
```suggestion
```

2024-04-01 17:08 UTC, matthew-buglass commented on my-webxr-app/tests/components/GenerateXYZ.test.tsx
> +// import { Vector3 } from 'three';
Remove the commented-out code
```suggestion
```

2024-04-01 17:08 UTC, matthew-buglass commented on my-webxr-app/tests/components/GenerateXYZ.test.tsx
> +// import { ReactThreeTestInstance } from '@react-three/test-renderer/dist/declarations/src/createTestInstance';
Remove the commented-out code
```suggestion
```

2024-04-01 19:11 UTC, Subzeero approved these changes
Looks good 🙌

2024-04-01 19:12 UTC, merged