Load csv
UniversityOfSaskatchewanCMPT371/term-project-2024-team-2 pull request #44
Opened 2024-01-25 04:13 UTC by LongQuanNguyen

Finish implementation of url and local file csv loading

2024-01-25 21:24 UTC, matthew-buglass requested changes
A few general notes, some of which we addressed at standup:

- We need to add some log4js logging
- We need to write unit tests for the loaders. @MitchWag01 is working on the spec
- I'd like to see some more details of what was done to test it, even some screenshots.
- We want so more details of what and why it was done, for example: "Why did we choose `papaparse`?"
- Do we need to commit the images for react and vite?
- We need to add some documentation of what the elements do and what arguments they take. If we go with something like [JSDoc](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) syntax, we can easily auto-build nice documentation later.
- From a testability and operation standpoint, the actual reading and parsing of the csv could be abstracted out functionally instead of in seperate react elements.

2024-01-25 21:24 UTC, matthew-buglass commented on src/components/UrlReader.tsx
Might want to make this name more explicit to include CSV, in-case we need multiple readers.

2024-01-25 21:24 UTC, matthew-buglass commented on src/components/LocalReader.tsx
> +function LocalReader({ setData }: { setData: (data: any[]) => void }) {
Might want to make this name more explicit to include CSV and the local refers to a local file reader, in-case we need multiple readers.

2024-01-25 21:24 UTC, matthew-buglass commented on src/components/UrlReader.tsx
> +                //console.table(results.data);
Does this need to be here?

2024-01-25 21:24 UTC, matthew-buglass commented on src/assets/grades.csv
If this is only for testing purposes, it should be under a `tests/assets/` type directory so that we can easily ignore it when we go to deploy.

Do we also need it to be this big?

2024-01-25 21:24 UTC, matthew-buglass commented on src/components/LocalReader.tsx
> +                //console.table(results.data);
Is this dead code?

2024-01-26 16:07 UTC, trangnguyen3010 commented on .gitignore
> +logs
the addition of a logging tool (in our case, log4js) along with some updates in README on how to use the framework could be a separate issue of its own. We can keep this issue and pull request focused solely on loading CSVs!

2024-01-26 16:09 UTC, trangnguyen3010 commented
> A few general notes, some of which we addressed at standup:
> 
> * We need to add some log4js logging
> * We need to write unit tests for the loaders. @MitchWag01 is working on the spec
> * I'd like to see some more details of what was done to test it, even some screenshots.
> * We want so more details of what and why it was done, for example: "Why did we choose `papaparse`?"
> * Do we need to commit the images for react and vite?
> * We need to add some documentation of what the elements do and what arguments they take. If we go with something like [JSDoc](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) syntax, we can easily auto-build nice documentation later.
> * From a testability and operation standpoint, the actual reading and parsing of the csv could be abstracted out functionally instead of in seperate react elements.

the addition of a logging tool (in our case, log4js) along with some updates in README on how to use the framework could be a separate issue of its own. We can keep this issue and pull request focused solely on loading CSVs!

2024-01-26 16:13 UTC, matthew-buglass commented
I agree that the logging addition could wait. My comments on reasoning were not README targeted, but to have a deeper discussion on the MR itself to aid in reviewing.

2024-01-27 23:38 UTC, closed without merging