63: Repository-wide .gitignore
UniversityOfSaskatchewanCMPT371/term-project-2024-team-2 pull request #70
Opened 2024-01-29 22:29 UTC by Subzeero

Closes #63

# What was the issue
Our `.gitignore` file was located in a subdirectory and was missing some necessary files to ignore.

# What was done and why
Moved the `.gitignore` file up to the repository root and added some common templates for Node.js, macOS, Windows, and JetBrains IDEs.

# How it was tested
N/A

2024-01-29 23:14 UTC, matthew-buglass approved these changes

2024-01-30 01:20 UTC, trangnguyen3010 requested changes
- [x] Prefix the commit with the issue number

2024-01-30 16:23 UTC, Subzeero commented
Hey guys, I was reviewing the a support pages from JetBrains and there are some files in the .idea folder that are supposed to be shared with Git. I have added these in the most recent push. These files are "needed" to be shared, so there shouldn't be any issues, but please check and let me know.

2024-02-01 04:06 UTC, matthew-buglass approved these changes
As this gets merged in, I would recommend letting everyone know the their local environment might change a bit with the .idea files being committed.

2024-02-01 06:22 UTC, trangnguyen3010 commented
I checked out the branch and have not seen any problems so far! 👍

2024-02-01 06:22 UTC, trangnguyen3010 approved these changes

2024-02-01 19:16 UTC, matthew-buglass commented on .idea/inspectionProfiles/Project_Default.xml
This acts as the default setting for the project. The idea files that are not ignored allow for a standard environment across all developers to assist in consistency.

2024-02-05 02:00 UTC, Subzeero commented on .gitignore
My understanding is that these files should be ignored everywhere. If it is not a direct file path, it should catchall.

2024-02-05 02:03 UTC, merged